name: schedule_scraping_script

on:
  schedule:
    - cron: "0 23 * * *"
  push:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Run a scraping script
        run: |
          echo "Python script"
          python3 scraping.py
