name: schedule_scraping_script

on:
  schedule:
    - cron: "0 23 * * *"
  push:

jobs:
  scraping:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-python@v4 # https://github.com/actions/setup-python
      with:
        python-version: '3.9.13'
    - run: pip install -r requirements.txt
    - name: Run a scraping script
      run: |
        echo "Run a scraping script"
        python3 scraping.py
    - name: Set current datetime as env variable
      env:
        TZ: 'Asia/Tokyo'
      run: echo "CURRENT_DATETIME=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
    - uses: stefanzweifel/git-auto-commit-action@v3.0.0 # https://github.com/stefanzweifel/git-auto-commit-action
      with:
        commit_message: Page was updated ${{ env.CURRENT_DATETIME }}
        ref: ${{ github.head_ref }}
